config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :username,uniqueness: { case_sensitive: false }, presence: true, length: { minimum: 3, maximum: 15}
    has_many :messages
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user

        if !logged_in?
            flash[:error] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end

    def create

    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
before_action :require_user
    def index
        @messages = Message.all
        @message = Message.new
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user
    def create
        message = current_user.messages.build(message_params)
        if message.save
           redirect_to root_path
        end
    end

    private

    def message_params
        params.require(:message).permit(:body)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :logged_in_redirect, onli: [:new, :create]
    def new
    end
  
    def create
      user = User.find_by(username: params[:session][:username])
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:success] = "You have successfully logged in"
        redirect_to root_path
      else
        flash.now[:error] = "There was something wrong with your login information"
        render 'new'
      end
    end
  
    def destroy
      session[:user_id] = nil
      flash[:success] = "You have successfully logged out"
      redirect_to login_path
    end

    private

    def logged_in_redirect
        if logged_in?
            flash[:error] = "You are already logged in"
            redirect_to root_path
        end
    end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
    <i class="circular orange coffee icon"></i>
    Say Something
  </h4>
  
  <div class="ui two column grid">
    <div class="twelve wide column">
      <div class="ui fluid raised card chatbox">
        <div class="content">
          <div class="ui feed">
          <%= render @messages %>
          </div>
        </div>
        <div class="extra content">
            <%= form_for(@message, html: {class: "ui reply form", role: "form"},url: message_path) do |f| %>
                <div class="field">
                    <div class="ui fluid icon input">
                        <%= f.text_field :body %>
                        <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %> 
                    </div>
                </div>
              <% end %>
        </div>
      </div>
    </div>
  
    <div class="four wide column">
      <div class="ui fluid raised card chatbox">
        <div class="content">
          <div class="ui inverted vertical menu">
            <a class="active item">
              Home
            </a>
            <a class="item">
              Messages
            </a>
            <a class="item">
              Friends
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>

    <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
        <div class="header">
            <%= message_content %>
        </div>
    </div>

<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Chatroom", root_path, class: "item" %>
<a class="item">
  Messages
</a>
<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if logged_in? %>
        <%= link_to "Logout", logout_path, method: :delete, class: "item" %>
      <% else %>
        <%= link_to "Log in", login_path, class: "item" %>
      <% end %>
    </div>
  </div>
  <% if !logged_in? %>
    <div class="item">
      <%= link_to "Log in", login_path, class: "ui primary button" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="ui small inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
    <div class="ui container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
        <div class="summary">
            <em><%= message.user.username %></em>: <%= message.body %>
        </div>
    </div>
</div>